#!/usr/bin/env bash
# Neon → AWS Postgres migration (Scenario A: EC2+Docker, Scenario B: RDS).
# Requires: aws CLI, libpq pg_dump/pg_restore (brew install libpq), .env with DATABASE_URL.
#
# Usage:
#   aws configure   # or export AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY
#   ./scripts/aws_postgres_migrate.sh provision-a   # create EC2 + Docker Postgres
#   ./scripts/aws_postgres_migrate.sh dump          # pg_dump Neon → /tmp/relocation_jobs.dump
#   ./scripts/aws_postgres_migrate.sh restore       # pg_restore into AWS (needs aws-postgres.env)
#   ./scripts/aws_postgres_migrate.sh cutover       # update local .env DATABASE_URL
#   ./scripts/aws_postgres_migrate.sh verify        # row counts + connection test
#
# State file (gitignored): aws-postgres.env — endpoint, password, elastic IP.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
STATE_FILE="$ROOT/aws-postgres.env"
DUMP_FILE="/tmp/relocation_jobs.dump"
REGION="${AWS_REGION:-eu-central-1}"
INSTANCE_TYPE="${AWS_INSTANCE_TYPE:-t4g.micro}"
DB_USER="relocation"
DB_NAME="relocation_jobs"
PROJECT_TAG="relocation-jobs-pg"

PG_BIN="${PG_BIN:-}"
if [[ -z "$PG_BIN" ]]; then
  if [[ -x /opt/homebrew/opt/libpq/bin/pg_dump ]]; then
    PG_BIN="/opt/homebrew/opt/libpq/bin"
  else
    PG_BIN="$(dirname "$(command -v pg_dump)")"
  fi
fi

log() { printf '[migrate] %s\n' "$*"; }
die() { printf '[migrate] ERROR: %s\n' "$*" >&2; exit 1; }

PYTHON="${ROOT}/.venv/bin/python3"
if [[ ! -x "$PYTHON" ]]; then
  PYTHON="$(command -v python3)"
fi

require_aws() {
  load_aws_env
  command -v aws >/dev/null 2>&1 || die "aws CLI not found (brew install awscli or pip install awscli)"
  aws sts get-caller-identity --region "$REGION" >/dev/null 2>&1 \
    || die "AWS credentials missing — add AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY to .env"
}

neon_database_url() {
  "$PYTHON" - <<PY
from pathlib import Path
from dotenv import load_dotenv
import os
load_dotenv(Path("$ROOT") / ".env")
print(os.environ.get("DATABASE_URL", ""))
PY
}

load_aws_env() {
  eval "$("$PYTHON" - <<PY
from pathlib import Path
from dotenv import load_dotenv
import os, shlex
load_dotenv(Path("$ROOT") / ".env")
for k in ("AWS_ACCESS_KEY_ID", "AWS_SECRET_ACCESS_KEY", "AWS_SESSION_TOKEN", "AWS_REGION"):
    v = os.environ.get(k)
    if v:
        print(f"export {k}={shlex.quote(v)}")
PY
)"
}

load_dotenv() {
  DATABASE_URL="$(neon_database_url)"
  [[ -n "$DATABASE_URL" ]] || die "DATABASE_URL not set in .env"
}

load_state() {
  [[ -f "$STATE_FILE" ]] || die "Missing $STATE_FILE — run provision-a first"
  # shellcheck disable=SC1090
  source "$STATE_FILE"
}

save_state() {
  umask 077
  cat >"$STATE_FILE" <<EOF
# Generated by aws_postgres_migrate.sh — do not commit
AWS_REGION=$REGION
SCENARIO=$SCENARIO
EC2_INSTANCE_ID=${EC2_INSTANCE_ID:-}
ELASTIC_IP=${ELASTIC_IP:-}
DB_USER=$DB_USER
DB_NAME=$DB_NAME
DB_PASSWORD=$DB_PASSWORD
DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${ELASTIC_IP}:5432/${DB_NAME}?sslmode=prefer
EOF
  log "Wrote $STATE_FILE"
}

random_password() {
  openssl rand -base64 24 | tr -d '/+=' | head -c 24
}

my_public_ip() {
  curl -sf --max-time 10 https://checkip.amazonaws.com | tr -d '\n'
}

cmd_dump() {
  load_dotenv
  [[ -n "${DATABASE_URL:-}" ]] || die "DATABASE_URL not set in .env"
  if [[ "$DATABASE_URL" == *"-pooler"* ]]; then
    log "WARNING: DATABASE_URL uses Neon pooler; pg_dump may fail. Use direct endpoint for dump."
  fi
  log "Dumping to $DUMP_FILE ..."
  "$PG_BIN/pg_dump" "$DATABASE_URL" \
    --no-owner --no-acl --format=custom -f "$DUMP_FILE"
  log "Dump OK: $(du -h "$DUMP_FILE" | awk '{print $1}')"
}

cmd_provision_a() {
  require_aws
  SCENARIO=A
  DB_PASSWORD="${DB_PASSWORD:-$(random_password)}"
  MY_IP="$(my_public_ip)"
  [[ -n "$MY_IP" ]] || die "Could not detect public IP for SSH rule"

  log "Region=$REGION instance=$INSTANCE_TYPE ssh_from=$MY_IP"

  VPC_ID="$(aws ec2 describe-vpcs --region "$REGION" \
    --filters Name=isDefault,Values=true \
    --query 'Vpcs[0].VpcId' --output text)"
  [[ "$VPC_ID" != "None" && -n "$VPC_ID" ]] || die "No default VPC in $REGION"

  SG_ID="$(aws ec2 create-security-group --region "$REGION" \
    --group-name "${PROJECT_TAG}-sg-$(date +%s)" \
    --description "Postgres for relocation-jobs" \
    --vpc-id "$VPC_ID" \
    --query GroupId --output text)"
  aws ec2 create-tags --region "$REGION" --resources "$SG_ID" \
    --tags Key=Project,Value="$PROJECT_TAG"

  aws ec2 authorize-security-group-ingress --region "$REGION" --group-id "$SG_ID" \
    --ip-permissions \
    "IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges=[{CidrIp=${MY_IP}/32,Description=ssh}]" \
    "IpProtocol=tcp,FromPort=5432,ToPort=5432,IpRanges=[{CidrIp=0.0.0.0/0,Description=postgres-render-local}]"

  AMI_ID="$(aws ec2 describe-images --region "$REGION" --owners 099720109477 \
    --filters "Name=name,Values=ubuntu/images/hvm-ssd-gp3/ubuntu-noble-24.04-arm64-server-*" \
              "Name=state,Values=available" \
    --query 'sort_by(Images, &CreationDate)[-1].ImageId' --output text)"
  [[ "$AMI_ID" != "None" && -n "$AMI_ID" ]] || die "Could not resolve Ubuntu 24.04 ARM AMI"

  USER_DATA="$(cat <<EOS
#!/bin/bash
set -eux
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y docker.io
systemctl enable docker
systemctl start docker
docker run -d --name pg --restart unless-stopped \\
  --memory=768m \\
  -e POSTGRES_USER=${DB_USER} \\
  -e POSTGRES_PASSWORD='${DB_PASSWORD}' \\
  -e POSTGRES_DB=${DB_NAME} \\
  -v pgdata:/var/lib/postgresql/data \\
  -p 5432:5432 \\
  postgres:16
EOS
)"
  USER_DATA_B64="$(printf '%s' "$USER_DATA" | base64)"

  INSTANCE_ID="$(aws ec2 run-instances --region "$REGION" \
    --image-id "$AMI_ID" \
    --instance-type "$INSTANCE_TYPE" \
    --security-group-ids "$SG_ID" \
    --user-data "$USER_DATA_B64" \
    --block-device-mappings '[{"DeviceName":"/dev/sda1","Ebs":{"VolumeSize":20,"VolumeType":"gp3","DeleteOnTermination":true}}]' \
    --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${PROJECT_TAG}},{Key=Project,Value=${PROJECT_TAG}}]" \
    --query 'Instances[0].InstanceId' --output text)"
  EC2_INSTANCE_ID="$INSTANCE_ID"
  log "Launched $INSTANCE_ID — waiting for running ..."
  aws ec2 wait instance-running --region "$REGION" --instance-ids "$INSTANCE_ID"

  ALLOC_ID="$(aws ec2 allocate-address --region "$REGION" --domain vpc --query AllocationId --output text)"
  aws ec2 associate-address --region "$REGION" --instance-id "$INSTANCE_ID" --allocation-id "$ALLOC_ID" >/dev/null
  ELASTIC_IP="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$ALLOC_ID" \
    --query 'Addresses[0].PublicIp' --output text)"

  log "Elastic IP: $ELASTIC_IP — waiting for Postgres (up to 3 min) ..."
  for _ in $(seq 1 36); do
  if PGPASSWORD="$DB_PASSWORD" "$PG_BIN/pg_isready" -h "$ELASTIC_IP" -p 5432 -U "$DB_USER" -d "$DB_NAME" >/dev/null 2>&1; then
    log "Postgres ready"
    save_state
    log "Next: ./scripts/aws_postgres_migrate.sh dump && ./scripts/aws_postgres_migrate.sh restore"
    return 0
  fi
  sleep 5
  done
  save_state
  die "Postgres not ready yet — check instance logs; state saved in $STATE_FILE"
}

cmd_restore() {
  load_state
  [[ -f "$DUMP_FILE" ]] || die "Missing $DUMP_FILE — run dump first"
  log "Restoring to ${ELASTIC_IP:-$DB_NAME} ..."
  "$PG_BIN/pg_restore" -d "$DATABASE_URL" \
    --no-owner --no-acl --clean --if-exists "$DUMP_FILE" \
    || log "pg_restore exited non-zero (often benign for extensions/roles)"
  cmd_verify_aws
}

cmd_verify_aws() {
  load_state
  PGPASSWORD="$DB_PASSWORD" "$PG_BIN/psql" "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
SELECT 'companies' AS tbl, COUNT(*) FROM companies
UNION ALL SELECT 'matching_jobs', COUNT(*) FROM matching_jobs
UNION ALL SELECT 'users', COUNT(*) FROM users
UNION ALL SELECT 'fetch_runs', COUNT(*) FROM fetch_runs;
SQL
}

cmd_verify_neon() {
  load_dotenv
  "$PG_BIN/psql" "$DATABASE_URL" -v ON_ERROR_STOP=1 <<'SQL'
SELECT 'companies' AS tbl, COUNT(*) FROM companies
UNION ALL SELECT 'matching_jobs', COUNT(*) FROM matching_jobs
UNION ALL SELECT 'users', COUNT(*) FROM users;
SQL
}

cmd_cutover() {
  load_state
  [[ -f "$ROOT/.env" ]] || die "No .env file"
  cp "$ROOT/.env" "$ROOT/.env.neon-backup-$(date +%Y%m%d%H%M%S)"
  if grep -q '^DATABASE_URL=' "$ROOT/.env"; then
    sed -i.bak "s|^DATABASE_URL=.*|DATABASE_URL=${DATABASE_URL}|" "$ROOT/.env"
    rm -f "$ROOT/.env.bak"
  else
    printf '\nDATABASE_URL=%s\n' "$DATABASE_URL" >>"$ROOT/.env"
  fi
  log "Updated .env DATABASE_URL (backup saved as .env.neon-backup-*)"
  log "Update Render dashboard DATABASE_URL to the same value, then redeploy."
  log "Restart local panel: python3 scripts/panel_server.py"
}

instance_security_group() {
  local instance_id="$1"
  aws ec2 describe-instances --region "$REGION" --instance-ids "$instance_id" \
    --query 'Reservations[0].Instances[0].SecurityGroups[0].GroupId' --output text
}

sg_has_cidr() {
  local sg_id="$1" port="$2" cidr="$3"
  aws ec2 describe-security-groups --region "$REGION" --group-ids "$sg_id" \
    --query "SecurityGroups[0].IpPermissions[?FromPort==\`$port\`].IpRanges[].CidrIp" --output text \
    | tr '\t' '\n' | grep -qx "$cidr"
}

authorize_port_cidr() {
  local sg_id="$1" port="$2" cidr="$3" desc="$4"
  if sg_has_cidr "$sg_id" "$port" "$cidr"; then
    log "sg $sg_id: port $port already allows $cidr"
    return 0
  fi
  aws ec2 authorize-security-group-ingress --region "$REGION" --group-id "$sg_id" \
    --ip-permissions "IpProtocol=tcp,FromPort=$port,ToPort=$port,IpRanges=[{CidrIp=$cidr,Description=$desc}]"
  log "sg $sg_id: opened port $port for $cidr ($desc)"
}

cmd_sync_sg() {
  require_aws
  load_state
  [[ -n "${EC2_INSTANCE_ID:-}" ]] || die "EC2_INSTANCE_ID missing in $STATE_FILE"
  MY_IP="$(my_public_ip)"
  [[ -n "$MY_IP" ]] || die "Could not detect public IP"
  SG_ID="${SECURITY_GROUP_ID:-$(instance_security_group "$EC2_INSTANCE_ID")}"
  [[ "$SG_ID" != "None" && -n "$SG_ID" ]] || die "Could not resolve security group"
  authorize_port_cidr "$SG_ID" 22 "${MY_IP}/32" "ssh-current"
  authorize_port_cidr "$SG_ID" 5432 "${MY_IP}/32" "postgres-local"
  authorize_port_cidr "$SG_ID" 5432 "0.0.0.0/0" "postgres-render"
  log "Security group $SG_ID synced for IP $MY_IP"
}

cmd_ensure_eip() {
  require_aws
  load_state
  [[ -n "${EC2_INSTANCE_ID:-}" ]] || die "EC2_INSTANCE_ID missing in $STATE_FILE"
  local current
  current="$(aws ec2 describe-addresses --region "$REGION" \
    --filters "Name=instance-id,Values=$EC2_INSTANCE_ID" \
    --query 'Addresses[0].PublicIp' --output text 2>/dev/null || true)"
  if [[ -n "$current" && "$current" != "None" ]]; then
    ELASTIC_IP="$current"
    log "Elastic IP already associated: $ELASTIC_IP"
  else
    local alloc
    alloc="$(aws ec2 allocate-address --region "$REGION" --domain vpc --query AllocationId --output text)"
    aws ec2 associate-address --region "$REGION" --instance-id "$EC2_INSTANCE_ID" --allocation-id "$alloc" >/dev/null
    ELASTIC_IP="$(aws ec2 describe-addresses --region "$REGION" --allocation-ids "$alloc" \
      --query 'Addresses[0].PublicIp' --output text)"
    log "Associated new Elastic IP: $ELASTIC_IP"
  fi
  DATABASE_URL="postgresql://${DB_USER}:${DB_PASSWORD}@${ELASTIC_IP}:5432/${DB_NAME}?sslmode=prefer"
  umask 077
  cat >"$STATE_FILE" <<EOF
# Generated by aws_postgres_migrate.sh — do not commit
AWS_REGION=$REGION
SCENARIO=${SCENARIO:-A}
EC2_INSTANCE_ID=$EC2_INSTANCE_ID
ELASTIC_IP=$ELASTIC_IP
SECURITY_GROUP_ID=${SECURITY_GROUP_ID:-$(instance_security_group "$EC2_INSTANCE_ID")}
DB_USER=$DB_USER
DB_NAME=$DB_NAME
DB_PASSWORD=$DB_PASSWORD
DATABASE_URL=$DATABASE_URL
EOF
  if grep -q '^DATABASE_URL=' "$ROOT/.env" 2>/dev/null; then
    sed -i.bak "s|^DATABASE_URL=.*|DATABASE_URL=${DATABASE_URL}|" "$ROOT/.env" && rm -f "$ROOT/.env.bak"
    log "Updated .env DATABASE_URL → $ELASTIC_IP"
  fi
}

cmd_status() {
  require_aws
  if [[ -f "$STATE_FILE" ]]; then
    # shellcheck disable=SC1090
    source "$STATE_FILE"
  fi
  if [[ -n "${EC2_INSTANCE_ID:-}" ]]; then
    aws ec2 describe-instances --region "$REGION" --instance-ids "$EC2_INSTANCE_ID" \
      --query 'Reservations[0].Instances[0].{State:State.Name,Type:InstanceType,IP:PublicIpAddress,SG:SecurityGroups[0].GroupId}' \
      --output table
  fi
  MY_IP="$(my_public_ip)"
  log "your public IP: $MY_IP"
  if [[ -n "${ELASTIC_IP:-}" ]]; then
    if nc -z -G 3 "$ELASTIC_IP" 5432 2>/dev/null; then
      log "postgres $ELASTIC_IP:5432 reachable"
    else
      log "postgres $ELASTIC_IP:5432 NOT reachable (run: $0 sync-sg)"
    fi
  fi
}

cmd_backup_cron_hint() {
  load_state
  cat <<EOF

Daily backup on EC2 (SSH in, then crontab -e):

0 3 * * * docker exec pg pg_dump -U ${DB_USER} ${DB_NAME} | gzip > /home/ubuntu/backups/\$(date +\\%F).sql.gz

EOF
}

usage() {
  cat <<EOF
Usage: $0 <command>

  provision-a   Launch EC2 t4g.micro + Docker Postgres 16 + Elastic IP (eu-central-1)
  dump          pg_dump from Neon (.env DATABASE_URL) → $DUMP_FILE
  restore       pg_restore dump into AWS Postgres (uses $STATE_FILE)
  verify        Row counts on AWS
  verify-neon   Row counts on Neon
  cutover       Point local .env at AWS (backs up Neon URL)
  sync-sg       Open SSH+Postgres for your current public IP (+ Render on 5432)
  ensure-eip    Associate Elastic IP if missing; update .env DATABASE_URL
  status        Instance + Postgres reachability check
  backup-hint   Print EC2 cron backup one-liner

Env overrides: AWS_REGION, AWS_INSTANCE_TYPE, DB_PASSWORD, PG_BIN
EOF
}

main() {
  local cmd="${1:-}"
  case "$cmd" in
    provision-a) cmd_provision_a ;;
    dump) cmd_dump ;;
    restore) cmd_restore ;;
    verify) cmd_verify_aws ;;
    verify-neon) cmd_verify_neon ;;
    cutover) cmd_cutover ;;
    sync-sg) cmd_sync_sg ;;
    ensure-eip) cmd_ensure_eip ;;
    status) cmd_status ;;
    backup-hint) cmd_backup_cron_hint ;;
    *) usage; exit 1 ;;
  esac
}

main "${1:-}"
