from __future__ import annotations

PANEL_PAGE_ROUTES: dict[str, frozenset[str]] = {
    "/": frozenset({"GET"}),
    "/panel": frozenset({"GET"}),
    "/app": frozenset({"GET"}),
    "/preview": frozenset({"GET"}),
    "/admin": frozenset({"GET"}),
    "/apply": frozenset({"GET"}),
    "/company/<country>/<path:company_slug>": frozenset({"GET"}),
    "/robots.txt": frozenset({"GET"}),
    "/sitemap.xml": frozenset({"GET"}),
}

PANEL_API_ROUTES: dict[str, frozenset[str]] = {
    "/api/auth/status": frozenset({"GET"}),
    "/api/auth/login": frozenset({"POST"}),
    "/api/auth/logout": frozenset({"POST"}),
    "/api/auth/register": frozenset({"POST"}),
    "/api/config": frozenset({"GET"}),
    "/api/countries": frozenset({"GET", "POST"}),
    "/api/countries/<country>": frozenset({"DELETE"}),
    "/api/countries/remove": frozenset({"POST"}),
    "/api/ats-types": frozenset({"GET"}),
    "/api/cities": frozenset({"GET"}),
    "/api/locations": frozenset({"GET", "POST"}),
    "/api/jobs": frozenset({"GET"}),
    "/api/jobs/applied": frozenset({"PATCH", "POST"}),
    "/api/jobs/rejected": frozenset({"PATCH", "POST"}),
    "/api/jobs/reapply": frozenset({"PATCH", "POST"}),
    "/api/jobs/ats-score": frozenset({"PATCH", "POST"}),
    "/api/jobs/waiting-referral": frozenset({"PATCH", "POST"}),
    "/api/jobs/not-for-me": frozenset({"POST"}),
    "/api/jobs/looking-to-apply": frozenset({"PATCH", "POST"}),
    "/api/jobs/seen": frozenset({"PATCH", "POST"}),
    "/api/jobs/pin": frozenset({"PATCH", "POST"}),
    "/api/board": frozenset({"GET"}),
    "/api/board/stats": frozenset({"GET"}),
    "/api/public/overview": frozenset({"GET"}),
    "/api/public/preview": frozenset({"GET"}),
    "/api/companies/<country>/<path:company_name>": frozenset({"GET"}),
    "/api/companies/applied": frozenset({"PATCH", "POST"}),
    "/api/companies/awaiting-response": frozenset({"PATCH", "POST"}),
    "/api/companies": frozenset({"POST", "DELETE"}),
    "/api/companies/remove": frozenset({"POST"}),
    "/api/companies/name": frozenset({"PATCH", "POST"}),
    "/api/companies/careers": frozenset({"PATCH", "POST"}),
    "/api/companies/city": frozenset({"PATCH", "POST"}),
    "/api/companies/fetch-problem": frozenset({"PATCH", "POST"}),
    "/api/companies/fetch-ok": frozenset({"POST"}),
    "/api/companies/jobs/manual-add": frozenset({"POST"}),
    "/api/companies/fetch": frozenset({"POST"}),
    "/api/fetch/status": frozenset({"GET"}),
    "/api/fetch/cancel": frozenset({"POST"}),
    "/api/fetch/history": frozenset({"GET"}),
    "/api/fetch": frozenset({"POST"}),
    "/api/fetch/attempts": frozenset({"GET"}),
    "/api/admin/dashboard": frozenset({"GET"}),
    "/api/admin/overview": frozenset({"GET"}),
    "/api/admin/catalog": frozenset({"GET"}),
    "/api/admin/users": frozenset({"GET"}),
    "/api/admin/fetch-runs": frozenset({"GET"}),
    "/api/admin/panel-stats": frozenset({"GET"}),
    "/api/admin/recent-jobs": frozenset({"GET"}),
    "/api/admin/config": frozenset({"GET"}),
    "/api/mcp/connect-info": frozenset({"GET"}),
    "/api/mcp/tokens": frozenset({"GET", "POST"}),
    "/api/mcp/tokens/<int:token_id>": frozenset({"DELETE"}),
    "/api/mcp/profile": frozenset({"GET", "PUT"}),
    "/api/mcp/master-resumes": frozenset({"GET"}),
    "/api/mcp/master-resumes/<slug>": frozenset({"GET", "PUT"}),
    "/api/mcp/master-resumes/<slug>/pdf": frozenset({"GET"}),
    "/api/mcp/master-resumes/<slug>/render": frozenset({"POST"}),
    "/api/mcp/project-masters": frozenset({"GET"}),
    "/api/mcp/project-masters/<slug>": frozenset({"GET", "PUT"}),
    "/api/mcp/project-masters/<slug>/pdf": frozenset({"GET"}),
    "/api/mcp/project-masters/<slug>/render": frozenset({"POST"}),
    "/api/mcp/companies/<country>/<path:company>/applications": frozenset({"GET"}),
    "/api/mcp/applications/<path:idempotency_key>": frozenset({"GET"}),
    "/api/mcp/applications/<path:idempotency_key>/tex": frozenset({"GET", "PUT"}),
    "/api/mcp/applications/<path:idempotency_key>/pdf": frozenset({"GET"}),
    "/api/mcp/applications/<path:idempotency_key>/render": frozenset({"POST"}),
}

V2_ONLY_ROUTES: frozenset[str] = frozenset({
    "/api/companies/<country>/<path:company_name>",
    "/api/fetch/attempts",
    "/api/board",
    "/api/board/stats",
})

REQUIRED_ROUTES: dict[str, frozenset[str]] = {
    **PANEL_PAGE_ROUTES,
    **PANEL_API_ROUTES,
}
